"""Small task-local history reader: direct sources or literal keyword excerpts."""

import hashlib
import json
import re
from urllib.parse import quote, unquote

from agent.tool_registry import ToolAttachment


def source_id(kind, row):
    return f"{kind}:{quote(row['key'], safe='')}@{row['version']}"


def record_text(kind, row, store=None):
    payload = row["payload"]
    if kind == "dialogue":
        if store is None:
            raise ValueError("Dialogue recall requires task storage")
        return store.artifacts.read_text(payload["ref"])
    if kind == "observation":
        return payload["text"]
    if kind == "note":
        text = payload["title"] + "\n" + payload["content"]
        extra = {k: payload[k] for k in ("retained", "unresolved", "resolution", "source_refs") if payload.get(k)}
        return text + ("\n" + json.dumps(extra, ensure_ascii=False) if extra else "")
    return json.dumps(payload, ensure_ascii=False, separators=(",", ":"))


def resolve_source(store, source):
    # A model-written note key must never shadow a program-assigned source ID.
    canonical = re.fullmatch(r"(note|event|observation|stage|measurement|dialogue|compaction):([^@#]+)@([1-9][0-9]*)(?:#([0-9]+))?", source)
    if canonical:
        kind, key, version, offset = canonical.groups()
        return kind, store.get(kind, unquote(key), int(version)), int(offset or 0)
    observation = store.db.get_agent_record(store.task_id, "observation", source)
    if observation is not None:
        return "observation", observation, 0
    # Other exact note keys remain usable even with reference punctuation.
    note = store.db.get_agent_record(store.task_id, "note", source)
    if note is not None:
        return "note", note, 0
    # References are generated by the reader. Models only copy them.
    offset = 0
    if "#" in source:
        source, suffix = source.rsplit("#", 1)
        offset = int(suffix)
        if offset < 0:
            raise ValueError("Invalid continuation source")
    if ":" in source:
        kind, key = source.split(":", 1)
        if kind not in {"note", "event", "observation", "stage", "measurement", "dialogue", "compaction"}:
            raise ValueError("Unknown history source; copy a returned source, note_key or observation_id, or query keywords")
        version = None
        if "@" in key:
            key, version = key.rsplit("@", 1)
            version = int(version)
        return kind, store.get(kind, unquote(key), version), offset
    note = store.db.get_agent_record(store.task_id, "note", source)
    if note is not None:
        return "note", note, offset
    return "observation", store.resolve_observation(source), offset


def read_history(store, args, ctx, initial_records):
    """Return bounded useful text or one historical image; never change action basis."""
    supplied = ctx.state.setdefault("history_supplied", set(initial_records))
    seen = ctx.state.setdefault("history_results", set())
    if args.source:
        kind, row, offset = resolve_source(store, args.source)
        rows = [(kind, row, offset)]
        total = 1
    else:
        terms = list(dict.fromkeys(re.findall(r"\S+", args.query.casefold())))
        matches = []
        for kind in ("note", "event", "observation", "stage", "measurement"):
            for row in store.records(kind):
                text = record_text(kind, row).casefold()
                score = sum(term in text or term in row["key"].casefold() for term in terms)
                if score:
                    matches.append((score, row["payload"].get("step", row["payload"].get("written_step", -1)), kind, row))
        # Match count first; deterministic recency ties. Distinct events remain distinct.
        matches.sort(key=lambda match: (match[0], match[1]), reverse=True)
        total = len(matches)
        rows = [(kind, row, None) for _, _, kind, row in matches[:6]]
    items, attachments = [], []
    budget = 12000 if args.full and args.source else 3000
    for kind, row, offset in rows:
        source = source_id(kind, row)
        item = {"source": source}
        if kind == "note":
            item["note_key"] = row["key"]
            if args.source and args.full:
                item["observation_ids"] = row["payload"].get("observation_ids", [])
        elif kind == "observation":
            item["observation_id"] = row["key"]
            if args.source:
                related = []
                for event in store.records("event"):
                    payload = event["payload"]
                    receipt = (payload.get("action_result") or {}).get("receipt") or {}
                    if row["key"] in (payload.get("observation_id"), receipt.get("observation_id"), receipt.get("effect_observation_id")):
                        related.append(source_id("event", event))
                if related:
                    item["event_sources"] = related[-6:]
                    if len(related) > 6:
                        item["omitted_event_count"] = len(related) - 6
        if args.view == "image":
            if kind != "observation" or not row["payload"].get("image_ref"):
                raise ValueError("Source has no image; request its text instead")
            data = store.artifacts.read_bytes(row["payload"]["image_ref"])
            signature = (source, "image", hashlib.sha256(data).hexdigest())
            if signature in seen:
                item["already_supplied"] = True
            else:
                attachments.append(ToolAttachment(
                    content=data, mime_type="image/jpeg" if data[:2] == b"\xff\xd8" else "image/png",
                    label=f"Historical observation {row['key']}; not an action reference",
                    observation_id=row["key"], actionable_coordinate_reference=False,
                ))
                seen.add(signature)
            items.append(item)
            continue
        text = record_text(kind, row, store)
        whole = hashlib.sha256(text.encode()).hexdigest()
        if (source, whole) in supplied and not args.full:
            item["already_supplied"] = True
            items.append(item)
            continue
        if offset is None:
            positions = [text.casefold().find(term) for term in terms if term in text.casefold()]
            offset = max(0, min(positions, default=0) - 100)
        size = budget if args.source else min(budget, 500)
        if size <= 0:
            break
        excerpt = text[offset:offset + size]
        end = offset + len(excerpt)
        signature = (source, "text", excerpt)
        if signature in seen:
            item["already_supplied"] = True
        else:
            item["text"] = excerpt
            seen.add(signature)
            budget -= len(excerpt)
        if offset > 0 or end < len(text):
            item["truncated"] = True
            if end < len(text):
                item["continue_source"] = f"{source}#{end}"
        else:
            supplied.add((source, whole))
        items.append(item)
    return {
        "items": items,
        **({"more_matches": total - len(items)} if total > len(items) else {}),
    }, attachments
