/* Console interface copy; task content and model responses retain their original language. */
export const english: Record<string, string> = {
  "工作空间": "WORKSPACE",
  "模型与账号": "Models & account",
  "配置 API": "Configure API",
  "升级正在进行，无需清除状态。请等待升级完成。": "An upgrade is in progress. No state reset is needed; please wait for it to finish.",
  "无法清除中断的升级状态，请检查后台日志后重试。": "Could not clear the interrupted upgrade state. Check the backend logs and try again.",
  "已清除中断的升级状态，可以重新检查更新并点击升级；本次操作不会继续下载或安装。": "Interrupted upgrade state cleared. Check for updates and start the upgrade again; this action does not resume downloading or installation.",
  "登录订阅或配置 API": "Subscription or API credentials",
  "手机连接": "Phone connection",
  "Wi-Fi、USB 与模拟器": "Wi-Fi, USB & emulators",
  "助手接入": "Assistant integration",
  "把手机任务交给助手": "Delegate phone tasks",
  "运行与学习": "Execution & learning",
  "任务预算与 Skill 偏好": "Budgets & Skill preferences",
  "查看与安装新版": "Check for and install updates",
  "连接模型、手机和助手，准备好你的手机任务工作空间。": "Connect your model, phone and assistant to set up your workspace.",
  "本机设置": "Local settings",
  "设置分类": "Settings categories",
  "第一次使用？": "Getting started?",
  "先配置模型，再连接手机，最后在助手中添加 ClickClick。": "Configure a model, connect your phone, then add ClickClick to your assistant.",
  "让助手协助接入": "Set up with your assistant",
  "选择适合你的连接方式，手机授权只需在设备上确认。": "Choose a connection method and confirm phone permissions on the device.",
  "设置每次任务和 Skill 学习的开销，按需开启额外检查。": "Set budgets for tasks and Skill learning, and enable optional checks.",
  "Codex / ChatGPT 订阅": "Codex / ChatGPT subscription",
  "用现有账号登录并授权": "Sign in with your existing account",
  "使用自己的模型服务与 API Key": "Use your model provider and API key",
  "保存后用于新任务": "Saved settings apply to new tasks",
  "保存设置": "Save settings",
  "正在读取版本信息…": "Loading version information…",
  "暂时无法读取版本信息，正在重新连接后台。": "Version information is temporarily unavailable. Reconnecting to the backend.",
  "当前使用源码部署。安装器版本可在这里升级；源码部署请按安装指南更新项目。": "You are running from source. Desktop installations can upgrade here; follow the installation guide to update a source deployment.",
  "模型的可用性取决于你的账号或 API 服务。": "Model availability depends on your account or API provider.",
  "为不同角色选择模型（可选）": "Choose models by role (optional)",
  "默认共用同一模型。需要时可为规划、执行和 Skill 学习分别选择，参数在下方按模型配置。": "Roles share a model by default. You can choose separate models for planning, execution and Skill learning, then configure each model below.",
  "。": ".",
  "、": ", ",
  "Thinking · 接口摘要": "Thinking · API summary",
  "未指定长度": "length unspecified",
  "接口返回的思考摘要（{value0}）；仅展示已返回内容。\n\n{value1}": "Reasoning summary returned by the API ({value0}); only returned content is shown.\n\n{value1}",
  "无法生成接入信息": "Could not generate connection details",
  "已复制": "Copied",
  "无法自动复制，请选中下方文本手动复制。": "Automatic copy failed. Select and copy the text below.",
  "在 AI 助手中添加 ClickClick": "Add ClickClick to your AI assistant",
  "让助手添加，或按它支持的方式手动添加。这里提供接入信息，注册由助手或你完成。": "Let your assistant add it, or add it manually using its supported method. Registration is performed by you or the assistant.",
  "正在生成本机接入信息…": "Generating local connection details…",
  "让助手添加（推荐）": "Let your assistant add it (recommended)",
  "把下面的提示词发给能执行本机命令、读取本机文件的助手。接入文件已生成，使用 stdio，无需填写监听地址或认证信息。": "Send this prompt to an assistant that can run commands and read files on this computer. The generated connection file uses stdio; no listening address or credential is needed.",
  "本机接入文件：": "Local connection file:",
  "复制助手接入提示词": "Copy assistant setup prompt",
  "查看提示词": "View prompt",
  "助手接入提示词": "Assistant setup prompt",
  "手动添加": "Add manually",
  "使用的助手": "Your assistant",
  "在本机": "Run on this computer in",
  "中执行：": ":",
  "MCP 注册命令": "MCP registration command",
  "复制注册命令": "Copy registration command",
  "助手配置文件：": "Assistant configuration file:",
  "MCP 配置内容": "MCP configuration",
  "复制配置内容": "Copy configuration",
  "添加后验证连接": "Verify the connection afterward",
  "按助手要求重新加载 MCP；如需重启客户端或新开会话，完成后在新会话发送下面的指令。注册完成还不代表连接成功。": "Reload MCP as required by your assistant. If it needs a restart or a new session, send the instruction below in that new session. Registration alone does not confirm connectivity.",
  "复制连接验证指令": "Copy verification instruction",
  "已停止等待授权，可重新登录。": "Stopped waiting for authorization. You can sign in again.",
  "未能停止后台授权，请检查连接后重试。": "Could not stop authorization. Check the connection and retry.",
  "授权超时，请重新登录。": "Authorization timed out. Please sign in again.",
  "授权完成，登录状态已保存在本机，可以派发手机任务。": "Authorized. Sign-in is saved locally; you can submit phone tasks.",
  "授权未完成，请重新登录。": "Authorization is incomplete. Sign in again.",
  "暂时无法查询授权状态，正在重试；也可以停止后重新登录。": "Could not check authorization. Retrying; you can also stop and sign in again.",
  "授权地址不符合预期，请重试。": "Unexpected authorization URL. Please retry.",
  "浏览器未打开新窗口，请点击下面的授权页链接。": "The browser did not open a window. Use the authorization link below.",
  "无法发起登录，请重试。": "Could not start sign-in. Please retry.",
  "订阅登录 ·": "Subscription sign-in ·",
  "检查中…": "Checking…",
  "已登录": "Signed in",
  "未登录": "Not signed in",
  "点击后保存当前设置并打开 OpenAI 授权页。授权完成后，ClickClick 自动保存本机登录状态。": "Save the current settings and open OpenAI authorization. ClickClick saves your local sign-in after authorization.",
  "设备授权码会显示在这个 ClickClick 页面": "Your device code will appear on this ClickClick page",
  "点击“登录并授权”后，在这里复制设备授权码，再粘贴到 OpenAI 授权页。若跳转后要求输入验证码，请返回此页获取。": "After clicking “Sign in and authorize”, copy the device code here and paste it into the OpenAI authorization page. If that page asks for a code, return here to get it.",
  "准备登录…": "Preparing sign-in…",
  "重新登录并授权": "Sign in and authorize again",
  "登录并授权": "Sign in and authorize",
  "设备授权码（填入 OpenAI 授权页）": "Device code (enter on the OpenAI authorization page)",
  "设备授权码已复制，请粘贴到 OpenAI 授权页。": "Device code copied. Paste it into the OpenAI authorization page.",
  "请选中上方设备授权码手动复制，粘贴到 OpenAI 授权页。": "Select and copy the device code above, then paste it into the OpenAI authorization page.",
  "复制设备授权码": "Copy device code",
  "打开授权页": "Open authorization page",
  "停止等待": "Stop waiting",
  "正在等待浏览器授权…完成后会自动更新，无需重启。": "Waiting for browser authorization… Status updates automatically; no restart needed.",
  "无法读取本机登录状态，请检查后台连接。": "Could not read local sign-in status. Check the backend connection.",
  "执行历史默认长度（tokens）": "Default execution history length (tokens)",
  "订阅执行历史长度（留空跟随默认）": "Subscription history length (blank inherits default)",
  "任务模型请求上限（留空使用 200 次保护上限）": "Task model request limit (blank uses the 200-request safeguard)",
  "任务设备动作上限（留空不额外限制）": "Task device action limit (blank adds no limit)",
  "任务总时限（秒，留空不额外限制）": "Task time limit (seconds; blank adds no limit)",
  "Skill 学习模型请求上限": "Skill learning model request limit",
  "Skill 学习动作上限": "Skill learning action limit",
  "Skill 学习总时限（秒）": "Skill learning time limit (seconds)",
  "自定义模型": "Custom model",
  "自定义模型…": "Custom model…",
  "模型名称或 ID": "Model name or ID",
  "填写服务商提供的模型名；未填写前缀时使用 openai/（兼容 API）。其他服务商请填写完整的服务商/模型 ID。": "Enter your provider’s model name. Names without a prefix use openai/ for compatible APIs. For other providers, enter the full provider/model ID.",
  "填写账号可用的模型名；未填写前缀时自动使用 chatgpt/。": "Enter a model available to your account. Names without a prefix use chatgpt/.",
  "使用此模型": "Use this model",
  "请先确认或取消自定义模型": "Confirm or cancel the custom model first",
  "请输入有效的模型名称或服务商/模型 ID，不要包含空格。": "Enter a valid model name or provider/model ID without spaces.",
  "模型前缀与接入方式不一致：订阅使用 chatgpt/，API 使用对应服务商前缀。": "The model prefix must match the access method: chatgpt/ for subscriptions, or the provider prefix for APIs.",
  "无法加载 Skill 偏好，请检查后台连接。": "Could not load Skill preferences. Check the backend connection.",
  "设置尚未加载": "Settings have not loaded",
  "设置已保存，新任务立即使用。模型凭据尚未测试；保存不会调用模型。运行中和暂停的任务需要先结束或取消。": "Settings saved for new tasks. Credentials have not been tested; saving does not call a model. Finish or cancel running and paused tasks before changing settings.",
  "未能保存设置": "Could not save settings",
  "模型与运行设置": "Models and execution settings",
  "选择 ClickClick 操作手机时使用的模型。所有角色使用 ClickClick 自己的 harness 和会话。": "Choose the models ClickClick uses to operate your phone. All roles use ClickClick’s own harness and sessions.",
  " 配置 API": " Configure API",
  " Codex / ChatGPT 订阅登录": " Codex / ChatGPT subscription sign-in",
  "切换后点击保存才会生效，两种方式的配置会分别保留。模型需支持图片与工具调用。": "Save to apply this choice. Both configurations are retained separately. Models must support images and tool calls.",
  "常用 GPT 模型可直接选择，实际可用性取决于账号或 API 服务。各角色也可直接选择预置模型，新增配置会沿用默认模型的参数": "Choose a GPT preset; availability depends on your account or API service. Roles can select presets directly. New configurations inherit the default model’s parameters",
  "与同一 API 服务的凭据": " and credentials for the same API service",
  "1. 选择模型": "1. Select models",
  "角色使用所选模型的思考强度等参数。点击“编辑所选模型参数”可展开下方对应模型的配置。": "Roles use their selected model’s reasoning and other parameters. “Edit selected model parameters” opens that model’s configuration below.",
  "选择默认模型": "Select the default model",
  "跟随 Planner + Reviewer": "Follow Planner + Reviewer",
  "跟随 Skill Learner": "Follow Skill Learner",
  "跟随默认模型": "Follow the default model",
  "服务默认": "Service default",
  "思考强度：{value0}": "Reasoning effort: {value0}",
  "未设置思考强度": "Reasoning effort not set",
  "{value0} · {value1}": "{value0} · {value1}",
  "请先选择模型": "Select a model first",
  "{value0}：编辑所选模型参数": "{value0}: edit selected model parameters",
  "编辑所选模型参数": "Edit selected model parameters",
  "2. 配置模型参数": "2. Configure model parameters",
  "在上方选好模型后，在这里设置 API 连接、思考强度等参数。同一模型的配置由使用它的角色共用。": "After choosing models above, configure API connections, reasoning effort and other parameters here. Roles using the same model share its configuration.",
  "· 模型配置": "· Model configuration",
  "默认": "Default",
  "使用此配置的角色：": "Roles using this configuration:",
  "暂未分配": "Not assigned yet",
  "。选择同一模型的角色共用以下参数。": ". Roles using this model share the parameters below.",
  "更换模型或自定义 ID": "Change model or use a custom ID",
  "模型": "Model",
  "模型 ID": "Model ID",
  "例如 openai/gpt-4.1": "For example, openai/gpt-4.1",
  "例如 chatgpt/gpt-5.6-sol，以账号实际可用模型为准": "For example, chatgpt/gpt-5.6-sol; use a model available to your account",
  "此模型的 API 连接配置": "API connection for this model",
  "API 地址": "API base URL",
  "（已保存，留空保留）": "(saved; leave blank to keep)",
  "HTTP User-Agent（可选，留空使用默认值）": "HTTP User-Agent (optional; blank uses the default)",
  "此模型的思考与高级参数": "Reasoning and advanced parameters for this model",
  "以下设置属于": "These settings belong to",
  "，会应用到所有使用它的角色。": " and apply to all roles using it.",
  "发送 reasoning 参数（模型需支持）": "Send reasoning parameters (model support required)",
  "推理强度": "Reasoning effort",
  "推理摘要": "Reasoning summary",
  "流式响应": "Streaming responses",
  "模型历史长度（tokens）": "Model history length (tokens)",
  "最大输入长度（tokens）": "Maximum input length (tokens)",
  "最大输出长度（tokens）": "Maximum output length (tokens)",
  "留空使用默认": "Leave blank to use the default",
  "工具调用策略": "Tool choice",
  "required（推荐）": "required (recommended)",
  "auto（模型兼容选项）": "auto (compatibility option)",
  "显式声明支持的参数（可选，逗号分隔）": "Explicit supported parameters (optional, comma separated)",
  "服务商 thinking 等额外请求参数（JSON 对象）": "Provider-specific thinking and extra request parameters (JSON object)",
  "已保存，留空保留；输入 {} 清除。内容不回显。": "Saved; blank keeps it. Enter {} to clear. Saved content is hidden.",
  "按服务商文档填写；留空不发送额外参数": "Follow your provider’s documentation; blank sends no extra parameters",
  "不同服务的 thinking 格式不同。请按实际服务文档配置，勿在此放任务指令。": "Thinking formats vary by provider. Follow the service’s documentation; do not put task instructions here.",
  "移除模型（先解除角色选择）": "Remove model (unassign roles first)",
  "添加自定义模型": "Add a custom model",
  "任务与 Skill 学习默认预算": "Default task and Skill learning budgets",
  "Skill 学习（自进化）会探索 App 的操作方法，生成待评审的可复用技能。这些预算限制每次学习的开销；保存预算不会启动学习。": "Skill learning explores app workflows and generates reusable skills for review. These budgets limit each learning run; saving them does not start learning.",
  "任务流程": "Task workflow",
  "Planner + Executor（默认）": "Planner + Executor (default)",
  "时限从创建任务开始计算，暂停不会延长。Skill 学习仍需每次确认模型开销和设备操作；结果需评审与验证，不会自动发布。": "Time limits start at task creation; pausing does not extend them. Each Skill learning run still requires consent to model costs and device actions. Results require review and validation; they are not published automatically.",
  "保存中…": "Saving…",
  "保存模型与运行设置": "Save model and execution settings",
  "本地任务统计与报告导出": "Local task statistics and report export",
  "记录任务统计与 Skill 改进线索（仅保存在本机）": "Record task statistics and Skill improvement hints (stored locally only)",
  "任务结束后记录成功/失败、重复动作等线索，供后续 Skill 学习参考。记录本身不会额外调用模型或操作手机。": "Record success, failure and repeated-action hints for later Skill learning. Recording does not call a model or operate the phone.",
  "允许在任务详情中手动导出统计报告（默认关闭）": "Allow manual statistics export from task details (off by default)",
  "报告可用于反馈问题，包含 App 包名、结果和动作计数，不含截图、任务指令、输入内容或设备标识。开启后可预览和下载，不会自动上传。": "Reports contain app package names, outcomes and action counts, but no screenshots, task instructions, entered content or device identifiers. You can preview and download them; nothing is uploaded automatically.",
  "ClickClick 新版 {value0} 已发布": "ClickClick {value0} is available",
  "ClickClick 更新检查或升级未完成": "ClickClick update check or upgrade did not finish",
  "查看更新并确认升级": "View updates and confirm upgrade",
  "等待更新器": "Waiting for updater",
  "下载并校验安装包": "Downloading and verifying the installer",
  "正在升级并重启后台": "Upgrading and restarting the backend",
  "升级成功": "Upgrade succeeded",
  "更新未完成": "Update did not finish",
  "更新操作未完成": "Update operation did not finish",
  "版本更新": "Version updates",
  "当前版本：": "Current version:",
  "自动检查新版（只检查版本信息，升级需确认）": "Check automatically (checks version information only; upgrades require confirmation)",
  "检查更新": "Check for updates",
  "上次检查：": "Last checked:",
  "发现新版": "New version available",
  "查看发布说明": "View release notes",
  "升级将重启后台。请先完成、暂停或取消手机任务；API 配置、任务记录和用户技能会保留。": "Upgrading restarts the backend. Finish, pause or cancel phone tasks first. API configuration, task history and user skills are preserved.",
  "确认升级至": "Confirm upgrade to",
  "暂无适用于当前平台的更新。": "No update is available for this platform.",
  "后台连接中断，正在重连。更新完成后会自动刷新状态；持续无法连接时请查看安装目录的 data/service.log。": "Backend disconnected; reconnecting. Status refreshes after the update. If it stays unavailable, check data/service.log in the installation directory.",
  "升级正在进行，请等待完成。下载和解压可能需要几分钟；完成后会自动重启后台并更新状态。": "Upgrade in progress. Downloading and extracting may take a few minutes. The backend will restart and the status will refresh automatically when finished.",
  "升级进程已停止，但升级状态尚未清除。清除后可重新发起升级；此操作不会继续下载或安装。": "The upgrade process has stopped, but its status was left behind. Clear it to retry the upgrade; this does not resume downloading or installation.",
  "清除中断的升级状态": "Clear interrupted upgrade state",
  "复制完整JSON": "Copy full JSON",
  "加载中…": "Loading…",
  "最终提交摘要（修正或回退后）": "Final committed summary (after correction or fallback)",
  "批次{value0} / {value1}": "Batch {value0} / {value1}",
  "摘要": "Summary",
  "降级/回退": "Degraded / fallback",
  "· 检查": "· Checks",
  " · 来源步骤 {value0}": " · Source step {value0}",
  "次请求 ·": "requests ·",
  "输入token": "input tokens",
  "本次候选（检查前）": "Candidate before checks",
  "已验证": "Verified",
  "未验证": "Unverified",
  " · 缓存": " · Cached",
  "忠实概率：": "Faithfulness probability:",
  "Jev实际输入：state + questions": "Actual Jev input: state + questions",
  "Jev原始输出": "Raw Jev output",
  "历史输入索引加载失败：": "Could not load historical input index:",
  "未保存实际请求（历史记录、缓存复用或检查未发出）；不以重建证据冒充请求。": "No actual request was saved (historical data, cached reuse or no check sent). Reconstructed evidence is not presented as an actual request.",
  "批次{value0}：已保存原始输出": "Batch {value0}: raw output saved",
  "完整判定报告与阈值": "Full assessment and thresholds",
  "Jev检查索引加载失败：": "Could not load Jev check index:",
  "加载当前压缩调用的Jev检查…": "Loading Jev checks for this compaction call…",
  "Jev 摘要检查 · 当前压缩调用": "Jev summary checks · Current compaction call",
  "每次摘要检查的实际Jev输入、输出及接纳结果。灰区和降级均不表示验证通过。": "Actual inputs, outputs and acceptance for each check. Gray-zone and degraded outcomes do not mean verification passed.",
  "暂无Jev检查记录。": "No Jev checks recorded.",
  "启用 Jev 摘要检查（默认关闭）": "Enable Jev summary checks (off by default)",
  "Jev 检查压缩后的任务摘要是否忠实于历史记录。开启后会将摘要和相关文字证据发送至下面的 Jev API，产生额外请求；关闭后不调用 Jev。保存设置不会发起测试请求。": "Jev checks whether compressed task summaries match the historical evidence. Enabling it sends summaries and related text evidence to the Jev API below and adds requests. Disabled mode makes no Jev calls. Saving does not send a test request.",
  "Jev API 配置": "Jev API configuration",
  "Jev API 地址": "Jev API base URL",
  "Jev 使用独立的 API Key；更换 API 地址时请重新填写 Key。": "Jev uses a separate API key. Enter a new key when changing its API base URL.",
  "Jev 模型 ID": "Jev model ID",
  "Jev 高级设置": "Advanced Jev settings",
  "检查模式": "Check mode",
  "参与摘要接纳": "Use checks for summary acceptance",
  "仅记录检查结果": "Record check results only",
  "Jev 请求超时（秒）": "Jev request timeout (seconds)",
  "Jev 服务异常时": "When Jev is unavailable",
  "跳过检查，保留降级记录": "Skip the check and record degradation",
  "保留原始历史，不接纳摘要": "Keep original history; do not accept the summary",
  "Skill 学习与任务统计报告": "Skill learning and task statistics reports",
  "正常任务结束不启动探索。公共技能由官方在测试环境学习与验证。": "Finishing a regular task does not start exploration. Public skills are learned and validated by maintainers in a test environment.",
  "本地任务统计、报告导出开关和学习默认预算可在": "Local task statistics, report export and learning budgets are available in",
  "设置": "Settings",
  "中调整。": ".",
  "报告导出默认关闭；报告不包含指令、截图、输入内容或设备标识。可手动下载后用于反馈，不会自动上传。": "Report export is off by default. Reports contain no instructions, screenshots, entered content or device identifiers. Download them manually for feedback; they are never uploaded automatically.",
  "预览任务统计报告": "Preview task statistics report",
  "下载报告": "Download report",
  "Skill 学习（自进化）会使用你配置的模型探索 App 操作方法，并实际操作当前设备。探索结果只进入待评审区；不会自动发布。": "Skill learning uses your configured model to explore app workflows and actually operates this device. Results enter the pending review area; they are not published automatically.",
  "模型请求上限": "Model request limit",
  "动作上限": "Action limit",
  "总时限（秒）": "Time limit (seconds)",
  "接受上述预算内的模型开销": "Accept model costs within these budgets",
  "允许本次探索操作设备": "Allow device actions for this exploration",
  "正在优化…": "Optimizing…",
  "优化我的工作流": "Optimize my workflow",
  "停止本次优化": "Stop this optimization",
  "本次未发现值得学习的规则。": "No useful new rules were found.",
  "探索结束；结果以评审与验证为准。": "Exploration ended; results remain subject to review and validation.",
  "未能启动优化": "Could not start optimization",
  "观测截图": "Observation screenshots",
  "已保存的任务画面，随观测记录更新。": "Saved task images, updated when observations are recorded.",
  "模型交互画面": "Model input image",
  "任务观测": "Task observation",
  " · 步骤 {value0}": " · Step {value0}",
  "使用说明": "How to use",
  "开启“跟随最新步骤”可查看新记录的观测截图；点击时间轴步骤可查看历史画面。": "Enable “Follow latest step” to see newly saved screenshots. Select a timeline step to view historical images.",
  "点击模型输入中的图片可查看该轮模型收到的画面。没有保存图片时会显示不可用。": "Select an image in model input to see the image received by that call. If no image was saved, it is shown as unavailable.",
  "当前步骤没有已保存的截图": "No saved screenshot for this step",
  "当前目标：": "Current goal:",
  "阶段技能：": "Stage skills:",
  "后续设想（待验证，将随执行反馈更新）": "Possible next stages (unverified; updated with execution feedback)",
  "计划版本": "Plan version",
  "已汇报阶段结果": "Reported stage outcomes",
  "当前目标": "Current goal",
  "反馈：": "Feedback:",
  "仅可交互": "Interactive only",
  "全部": "All",
  "此分析是保留的检查点，尚未覆盖最新交流。": "This analysis is a retained checkpoint and does not include the latest conversation.",
  "轨迹分析 · 模型判断": "Trace analysis · Model assessment",
  "提案 / 审查结论 · 模型判断": "Proposal / review conclusion · Model assessment",
  "主机返回的学习结束结果 · 接收与收益验证分开解释": "Host-reported learning outcome · Acceptance and benefit validation are separate",
  "引用与实际读取记录": "Citations and actual reads",
  "已持久化交流 ·": "Persisted conversation ·",
  "条消息 · 图片字节按原记录省略": "messages · Image bytes omitted as in the original record",
  "请求的工具及参数": "Requested tools and arguments",
  "完整观测记录": "Full observation record",
  "来自 pending 元数据的独立审查结论。没有保存的模型轮次仍为 unknown。": "Independent review from pending metadata. Missing model rounds remain unknown.",
  "Reviewer 独立审查 · 模型判断": "Independent Reviewer assessment · Model assessment",
  "候选预审": "Candidate pre-review",
  "验证记录 · 以实际匹配和评测证据为准": "Validation records · Based on actual matches and evaluation evidence",
  "适用条件与收益主张 · 模型判断": "Applicability and benefit claims · Model assessment",
  "· 累计快照": "· Cumulative snapshot",
  "查看候选正文和差异": "View candidate content and diff",
  "Learner 分析和 Reviewer 审查均为模型判断；探索执行和普通复验从各自任务原始记录读取。未记录的结果或 token 成本为 unknown。": "Learner and Reviewer conclusions are model assessments. Exploration and regular validation outcomes come from their original task records. Unrecorded outcomes and token costs remain unknown.",
  "学习运行中": "Learning in progress",
  "学习会话": "Learning session",
  "刷新记录": "Refresh records",
  "跟随最新记录": "Follow latest records",
  "上一页会话": "Previous sessions",
  "个会话": "sessions",
  "下一页会话": "Next sessions",
  "结束时累计成本": "Cumulative cost at completion",
  "会话累计采样快照": "Cumulative session snapshot",
  "，不按条目相加 · 记录至": "; do not sum entries · Recorded through",
  "· 打开执行轨迹": "· Open execution trace",
  "· 原任务不可用，执行结果 unknown": "· Original task unavailable; execution outcome unknown",
  "候选": "Candidate",
  "显示": "Showing",
  "条轨迹；其余保留在原始记录中。": "trace entries; remaining entries are retained in the original records.",
  "更早记录": "Earlier records",
  "最新记录": "Latest records",
  "另有": "Another",
  "个候选，打开现有技能列表查看": "candidates; open the existing skills list to inspect",
  "没有已持久化的": "No persisted",
  "学习": "learning",
  "记录。历史缺失不代表未执行。": "records. Missing history does not mean nothing was executed.",
  "此任务尚无可展示的学习会话。启动个人优化后，记录会在此更新。": "No learning sessions to display for this task yet. Start workflow optimization to see records here.",
  "上一页结果": "Previous outcomes",
  "个结束结果": "completed outcomes",
  "下一页结果": "Next outcomes",
  "学习结束记录 ·": "Learning completion record ·",
  "原始结束结果": "Raw completion result",
  "截图不可用": "Screenshot unavailable",
  "任务截图": "Task screenshot",
  "语义树": "Semantic tree",
  "{value0} 个元素": "{value0} elements",
  "排队": "Queued",
  "运行中": "Running",
  "正在暂停": "Pausing",
  "已暂停": "Paused",
  "运行时完成": "Runtime completed",
  "运行时失败": "Runtime failed",
  "已取消": "Cancelled",
  "跟随最新步骤 on": "Follow latest step on",
  "跟随最新步骤 off": "Follow latest step off",
  "跟随最新步骤": "Follow latest step",
  "默认模型": "Default model",
  " · 含预留上界": " · Includes reserved upper bounds",
  "{value0} 次请求 · {value1} 次动作 · {value2} s · tokens {value3}{value4}": "{value0} requests · {value1} actions · {value2} s · tokens {value3}{value4}",
  "任务画面": "Task images",
  "已保存的观测截图": "Saved observation screenshots",
  "打开任务详情，可在右侧查看观测截图。开启“跟随最新步骤”会随任务记录更新；选择历史步骤或模型输入图片可回看对应画面。": "Open task details to view screenshots on the right. Follow the latest step to see new records; select historical steps or model input images to inspect their saved images.",
  "截图属于历史记录，不能据此确认手机当前状态。": "Screenshots are historical records and do not confirm the phone’s current state.",
  "任务": "Tasks",
  "设备": "Devices",
  "技能": "Skills",
  "请求未完成，请检查填写内容。": "Request did not finish. Check your inputs.",
  "请在这台电脑通过 localhost 打开 Console 设置；也可使用安装器的设置入口。": "Open Console settings through localhost on this computer, or use the installer’s settings entry.",
  "操作未完成": "Operation did not finish",
  "正在连接本机设置…": "Connecting to local settings…",
  "选择订阅登录或 API，设置任务预算，连接手机，在 AI 助手中添加 ClickClick。": "Choose subscription sign-in or API, set task budgets, connect your phone, and add ClickClick to your AI assistant.",
  "重新连接本机设置": "Reconnect to local settings",
  "连接 Android": "Connect Android",
  "Wi-Fi（Android 11 及以上，不需要数据线）": "Wi-Fi (Android 11+, no cable needed)",
  "配对地址与端口": "Pairing address and port",
  "手机配对码页面显示的 IP:端口": "IP:port shown on the phone’s pairing-code page",
  "六位配对码": "Six-digit pairing code",
  "配对电脑与手机": "Pair computer and phone",
  "连接地址与端口": "Connection address and port",
  "无线调试主页面的 IP:端口，通常不同于配对端口": "IP:port on the wireless debugging main page; usually different from the pairing port",
  "ADB 已连接。后台会初始化 Collector；让助手调用 get_status 检查环境步骤与待授权事项。": "ADB connected. The backend initializes Collector; ask your assistant to call get_status to check setup steps and pending permissions.",
  "连接设备": "Connect device",
  "USB 数据线": "USB cable",
  "模拟器": "Emulator",
  "Android 10 及以下使用 Wi-Fi": "Wi-Fi on Android 10 and older",
  "检查已连接设备": "Check connected devices",
  "ADB 在线": "ADB online",
  "新建": "New",
  "正式技能": "Published skills",
  "待审 Pending": "Pending review",
  "保存": "Save",
  "确认删除正式技能 {value0}？": "Delete published skill {value0}?",
  "删除": "Delete",
  "选择左侧 pending 条目查看 diff": "Select a pending item on the left to view its diff",
  "批准": "Approve",
  "拒绝": "Reject",
  "处理中…": "Processing…",
  "恢复任务": "Resume task",
  "暂停任务": "Pause task",
  "确认强制终止该任务？": "Force-stop this task?",
  "正在停止…": "Stopping…",
  "强制终止": "Force stop",
  "Trace 流": "Trace stream",
  "Jev 摘要检查": "Jev summary checks",
  "Skill 学习": "Skill learning",
  "终止": "Stop",
  "输入指令，例如：打开设置并关闭蓝牙": "Enter a goal, for example: open Settings and turn off Bluetooth",
  "任务结束仅保留本地学习线索，不额外调用模型或操作设备。可在任务详情关闭记录。": "Finished tasks retain local learning hints only; they do not call models or operate devices. Recording can be disabled in task details.",
  "提交中…": "Submitting…",
  "每页": "Per page",
  "每页任务数": "Tasks per page",
  "10 条": "10 tasks",
  "20 条": "20 tasks",
  "上一页": "Previous page",
  "正在索引历史任务 · 已发现 {value0} 条": "Indexing task history · {value0} records found",
  "第 {value0} / {value1} 页 · 共 {value2} 条": "Page {value0} / {value1} · {value2} records",
  "第 {value0} 页": "Page {value0}",
  "下一页": "Next page",
  "历史任务索引暂不可用，稍后重试。": "Task history index is temporarily unavailable. Retry later.",
  "模型与订阅登录请前往": "For models and subscription sign-in, go to",
  "Android 11+：电脑和手机连接同一 Wi-Fi；设置→开发者选项→无线调试→使用配对码配对。提供该页面的 IP:配对端口和六位配对码；配对后返回无线调试主页面，使用 IP:连接端口。两种端口不同，不猜测 5555。": "Android 11+: connect your computer and phone to the same Wi-Fi. Open Settings → Developer options → Wireless debugging → Pair device with pairing code. Enter that page’s IP:pairing port and six-digit code. After pairing, return to the main Wireless debugging page and use its IP:connection port. These are different ports; do not assume 5555.",
  "开启开发者选项和 USB 调试；使用支持数据传输的数据线，解锁手机并接受此电脑的调试授权。Windows 若不识别设备，按手机厂商说明安装 USB 驱动。": "Enable Developer options and USB debugging. Use a data-capable cable, unlock the phone and approve this computer. On Windows, install your phone manufacturer’s USB driver if the device is not detected.",
  "启动 Android 8+/API 26 模拟器并等待开机。ADB 可自动识别时直接检查设备；否则使用模拟器显示的实际 ADB 地址/端口连接，不重建或清空已有实例。": "Start an Android 8+/API 26 emulator and wait for it to boot. Check devices if ADB detects it automatically; otherwise connect using the emulator’s actual ADB address and port. Keep existing instances and data.",
  "Android 10 及以下通常需先 USB 连接并授权，再由用户明确选择开启 adb tcpip；之后用手机实际 IP 和端口连接。手机重启后可能需重新开启。": "Android 10 and earlier usually require an authorized USB connection first, followed by explicitly enabling adb tcpip. Then connect with the phone’s actual IP and port. You may need to enable it again after a phone restart.",
  "其他 MCP 助手": "Other MCP assistant",
  "请先完成或取消未结束的任务（包括暂停任务）及个人优化，再保存模型与运行设置。": "Finish or cancel unfinished tasks (including paused tasks) and Skill learning before saving model and runtime settings.",
  "订阅授权进行中，请先完成或停止授权。": "Finish or cancel the ongoing subscription authorization first.",
  "配置无效：请检查模型、角色、API Key、地址及额外 JSON 参数。": "Invalid configuration: check models, roles, API keys, URLs and additional JSON parameters.",
  "无法保存本机设置，请检查数据目录权限。": "Cannot save local settings. Check data directory permissions.",
  "设置已保存，新任务立即使用；保存不会发起模型请求。": "Settings saved. New tasks use them immediately; saving does not send model requests.",
  "无法发起订阅授权，请检查网络后重试。": "Cannot start subscription authorization. Check your network and retry.",
  "授权未完成或已超时，请重新登录。": "Authorization is incomplete or expired. Sign in again.",
  "已有授权进行中，请先完成或停止授权。": "Finish or cancel the existing authorization first.",
  "暂无进行中的授权，请重新登录。": "No authorization is in progress. Sign in again."
};
